/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;


import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.ChatLinks;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatLinksRecord extends TableRecordImpl<ChatLinksRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.chat_links.chat</code>.
     */
    public void setChat(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.chat_links.chat</code>.
     */
    @Nullable
    public Long getChat() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.chat_links.link_id</code>.
     */
    public void setLinkId(@Nullable Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.chat_links.link_id</code>.
     */
    @Nullable
    public Long getLinkId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return ChatLinks.CHAT_LINKS.CHAT;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return ChatLinks.CHAT_LINKS.LINK_ID;
    }

    @Override
    @Nullable
    public Long component1() {
        return getChat();
    }

    @Override
    @Nullable
    public Long component2() {
        return getLinkId();
    }

    @Override
    @Nullable
    public Long value1() {
        return getChat();
    }

    @Override
    @Nullable
    public Long value2() {
        return getLinkId();
    }

    @Override
    @NotNull
    public ChatLinksRecord value1(@Nullable Long value) {
        setChat(value);
        return this;
    }

    @Override
    @NotNull
    public ChatLinksRecord value2(@Nullable Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public ChatLinksRecord values(@Nullable Long value1, @Nullable Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatLinksRecord
     */
    public ChatLinksRecord() {
        super(ChatLinks.CHAT_LINKS);
    }

    /**
     * Create a detached, initialised ChatLinksRecord
     */
    @ConstructorProperties({ "chat", "linkId" })
    public ChatLinksRecord(@Nullable Long chat, @Nullable Long linkId) {
        super(ChatLinks.CHAT_LINKS);

        setChat(chat);
        setLinkId(linkId);
    }

    /**
     * Create a detached, initialised ChatLinksRecord
     */
    public ChatLinksRecord(ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos.ChatLinks value) {
        super(ChatLinks.CHAT_LINKS);

        if (value != null) {
            setChat(value.getChat());
            setLinkId(value.getLinkId());
        }
    }
}
